BOARD_TAG			= uno
ARDUINO_PORT		= /dev/ttyUSB0
#ARDUINO_LIBS		= 
ISP_PORT			= /dev/ttyUSB0
ISP_PROG			= stk500v1
#ARDUINO_VAR_PATH	= $(HOME)/sketchbook/hardware/attiny/variants
#BOARDS_TXT			= $(HOME)/sketchbook/hardware/attiny/boards.txt

include /usr/share/arduino/Arduino.mk

# vi: noexpandtab ts=4
